---
azure_network: true
manage_vnet: true
vnet_peering: true
manage_nsg: true
manage_subnet: true

azure_vnet: vnet-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}
azure_vnet_link: vnet-link-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}
azure_subnet: subnet-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}
azure_subnet_nsg: nsg-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}
azure_public_ip:
  name: pip-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}-{{ inventory_hostname }}
  config_name: pip-config-{{ infrastructure_type }}-{{ network_zone }}-{{ deployment_environment }}-{{ inventory_hostname }}

azure_networks:
  - name: public
    vnet: 10.1.0.0/29
    subnet: 10.1.0.0/29
  - name: intra_mgmt
    vnet: 10.1.1.0/24
    subnet: 10.1.1.0/24
  - name: intra_work
    vnet: 10.1.2.0/24
    subnet: 10.1.2.0/24
  - name: dmz_work
    vnet: 10.1.3.0/24
    subnet: 10.1.3.128/25
  - name: dmz_mgmt
    vnet: 10.1.3.0/24
    subnet: 10.1.3.0/29

azure_vnet_address_prefix_public: "{{ (azure_networks | selectattr('name', 'match', 'public') | list)[0].vnet }}"
azure_vnet_address_prefix_mgmt_intra: "{{ (azure_networks | selectattr('name', 'match', 'intra_mgmt') | list)[0].vnet }}"
azure_vnet_address_prefix_work_intra: "{{ (azure_networks | selectattr('name', 'match', 'intra_work') | list)[0].vnet }}"
azure_vnet_address_prefix_work_dmz: "{{ (azure_networks | selectattr('name', 'match', 'dmz_work') | list)[0].vnet }}"

azure_subnet_address_prefix_public: "{{ (azure_networks | selectattr('name', 'match', 'public') | list)[0].subnet }}"
azure_subnet_address_prefix_mgmt_intra: "{{ (azure_networks | selectattr('name', 'match', 'intra_mgmt') | list)[0].subnet }}"
azure_subnet_address_prefix_workload_servers_intra: "{{ (azure_networks | selectattr('name', 'match', 'intra_work') | list)[0].subnet }}"
azure_subnet_address_prefix_workload_servers_dmz: "{{ (azure_networks | selectattr('name', 'match', 'dmz_work') | list)[0].subnet }}"
azure_subnet_address_prefix_mgmt_tools_dmz: "{{ (azure_networks | selectattr('name', 'match', 'dmz_mgmt') | list)[0].subnet }}"
