---
satellite_config_realms:
  - name: "{{ azure_dns_private_dns_zone | upper }}"
    realm_proxy: "{{ groups.satellite | first }}"
    realm_type: "Red Hat Identity Management"
    state: present
    locations:
      - Intranet
