---
controller_credentials:
  - credential_type: Machine
    name: "Machine Credential"
    description: "SSH Machine Connection with IdM credentials"
    organization: "{{ aap_config_organization }}"
    inputs:
      username: "{{ default_ssh_vm_user }}"
      password: "{{ techuser_ansible_global_password }}"

  - credential_type: Insights
    name: "Insights Credential"
    description: "Insights Credential"
    organization: "{{ aap_config_organization }}"
    inputs:
      username: "{{ hostvars[groups.satellite | first]['satellite_rhsm_username'] }}"
      password: "{{ hostvars[groups.satellite | first]['satellite_rhsm_password'] }}"

  - credential_type: Source Control
    name: "GitHub Source Credential"
    description: "GitHub Credential"
    organization: "{{ aap_config_organization }}"
    inputs:
      username: "{{ github_username }}"
      ssh_key_data: "{{ github_private_key }}"

  - credential_type: Vault
    name: "Vault Credential"
    description: "Vault Credential"
    organization: "{{ aap_config_organization }}"
    inputs:
      vault_password: "{{ vault_password }}"

  - credential_type: Vault
    name: "New Vault Credential"
    description: "New Vault Credential that use in vault password change process"
    organization: "{{ aap_config_organization }}"
    inputs:
      vault_password: "{{ vault_password }}"
      vault_id: 'new_vault_password'

  - credential_type: Red Hat Satellite 6
    name: "Satellite Credential"
    description: "Satellite Credential"
    organization: "{{ aap_config_organization }}"
    inputs:
      host: "https://{{ groups.satellite | first }}"
      username: "{{ hostvars[groups.satellite | first]['satellite_username'] }}"
      password: "{{ hostvars[groups.satellite | first]['satellite_password'] }}"

  - credential_type: Machine
    name: "Demo Credential"
    state: absent
